use_frameworks!

platform :ios, '8.0'

target 'PYTBaseViewController_Example' do
  pod 'PYTBaseViewController', :path => '../'

  target 'PYTBaseViewController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
